ALTER TABLE pruebas123_entries ADD COLUMN IF NOT EXISTS thread_id UUID;
ALTER TABLE pruebas123_entries ADD COLUMN IF NOT EXISTS alias TEXT;
ALTER TABLE pruebas123_entries ADD COLUMN IF NOT EXISTS verified BOOLEAN NOT NULL DEFAULT false;
